       version: '3.8'
       services:
         postgres_db:
           image: postgres:13
           container_name: aml_postgres
           environment:
             POSTGRES_USER: pawel_j
             POSTGRES_PASSWORD: natalia_1997
             POSTGRES_DB: aml_db
           ports:
             - "5432:5432"
           volumes:
             - postgres_data:/var/lib/postgresql/data

       volumes:
         postgres_data: